# Generated by Django 2.2 on 2020-12-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMainCategory', models.CharField(default='', editable=False, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', editable=False, max_length=2000)),
                ('nameMainCategory', models.CharField(default='', max_length=20000)),
                ('nameSubCategory', models.CharField(max_length=20000)),
                ('price', models.CharField(max_length=20000)),
                ('article', models.CharField(max_length=20000)),
                ('picture_url', models.CharField(max_length=20000)),
                ('characteristic', models.CharField(max_length=20000)),
                ('description', models.CharField(max_length=20000)),
                ('goods_url', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubCategory', models.CharField(default='', editable=False, max_length=2000)),
                ('nameMainCategory', models.CharField(max_length=20000)),
            ],
        ),
    ]
