# Generated by Django 2.2 on 2020-12-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201220_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nameMainCategory',
            new_name='name_main_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nameSubCategory',
            new_name='name_sub_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='nameMainCategory',
            new_name='name_main_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='nameSubCategory',
            new_name='name_sub_category',
        ),
    ]
