# Generated by Django 2.2 on 2021-03-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_main_category',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_sub_category',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_main_category',
            field=models.CharField(max_length=2000),
        ),
    ]
